version: '2.18.1'
services:
  postgres:
    image: postgres:14.8-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${USER_DATABASE}
      POSTGRES_PASSWORD: ${PASSWORD_DATABASE} 
      POSTGRES_DB: ${NAME_DATABASE}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - docker-compose_serverpulse_net

  django:
    image: serverpulse:latest
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      NAME_DATABASE: ${NAME_DATABASE}
      USER_DATABASE: ${USER_DATABASE}
      PASSWORD_DATABASE: ${PASSWORD_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
    volumes:
      - /home/dllg/Documentos/ProgramaciónSegura/nuevoProyFin/serverPulse:/app
    networks:
      - docker-compose_serverpulse_net
    
  nginx:
    image: nginx:stable-bullseye
    restart: always
    ports:
      #- 80:80 # development enviroment
      - 443:443 # production enviroment
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - /home/dllg/Documentos/ProgramaciónSegura/nuevoProyFin/serverPulse/static:/static/
    depends_on:
      - django
    networks:
      - docker-compose_serverpulse_net
    

networks:
  docker-compose_serverpulse_net:
    driver: bridge