# Generated by Django 4.1.5 on 2023-05-31 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmonGlobal',
            fields=[
                ('nickname', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('chat_id', models.CharField(max_length=10, unique=True)),
                ('token_bot', models.CharField(max_length=50, unique=True)),
                ('intentos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('timestamp_ultimo_intento', models.DateTimeField()),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Sysadmin',
            fields=[
                ('nickname', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('chat_id', models.CharField(max_length=10, unique=True)),
                ('token_bot', models.CharField(max_length=50, unique=True)),
                ('intentos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('timestamp_ultimo_intento', models.DateTimeField()),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(protocol='IPv4')),
                ('password', models.CharField(max_length=15, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Indeterminado'), (1, 'Activo'), (2, 'Apagado')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('sysadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.sysadmin')),
            ],
        ),
    ]
