# Generated by Django 4.1.5 on 2023-06-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='passwd',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='password',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='sysadmin',
            name='passwd',
            field=models.CharField(max_length=48),
        ),
    ]
