# Generated by Django 4.1.5 on 2023-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admonglobal',
            name='timestamp_token_doble_autenticacion',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admonglobal',
            name='token_doble_autenticacion',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sysadmin',
            name='timestamp_token_doble_autenticacion',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sysadmin',
            name='token_doble_autenticacion',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ipv4_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
