# Generated by Django 4.1.5 on 2023-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admonglobal_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='admonglobal_set', to='auth.permission'),
        ),
    ]
