# Generated by Django 4.1.5 on 2023-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_admonglobal_timestamp_token_doble_autenticacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admonglobal',
            old_name='token_doble_autenticacion',
            new_name='token_double_auth',
        ),
        migrations.RenameField(
            model_name='sysadmin',
            old_name='token_doble_autenticacion',
            new_name='token_double_auth',
        ),
        migrations.AddField(
            model_name='admonglobal',
            name='autorize_account',
            field=models.BooleanField(default=False),
        ),
    ]
