# Generated by Django 4.1.5 on 2023-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_admonglobal_passwd_alter_servidor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='passwd',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sysadmin',
            name='passwd',
            field=models.CharField(max_length=128),
        ),
    ]
