# Generated by Django 4.1.5 on 2023-06-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_admonglobal_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysadmin',
            name='salt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sysadmin', to='auth_app.salt'),
        ),
    ]
