# Generated by Django 4.1.5 on 2023-06-03 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0002_alter_admonglobal_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admonglobal',
            old_name='password',
            new_name='passwd',
        ),
        migrations.RenameField(
            model_name='admonglobal',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='admonglobal',
            name='user_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
