# Generated by Django 4.1.5 on 2023-06-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_admonglobal_passwd_alter_servidor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salt',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='salt',
            name='object_id',
        ),
    ]
