# Generated by Django 4.1.5 on 2023-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_password_admonglobal_passwd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admonglobal',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admonglobal',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admonglobal',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='admonglobal',
            name='token_session',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
