# Generated by Django 4.1.5 on 2023-06-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_salt_content_type_remove_salt_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salt',
            name='salt_value',
            field=models.CharField(max_length=128),
        ),
    ]
