# Generated by Django 4.1.5 on 2023-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_timestamp_token_doble_autenticacion_sysadmin_timestamp_token_double_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admonglobal',
            old_name='timestamp_token_doble_autenticacion',
            new_name='timestamp_token_double_auth',
        ),
    ]
