# Generated by Django 4.1.5 on 2023-06-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_admonglobal_options_alter_admonglobal_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_ultimo_intento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='token_double_auth',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
