# Generated by Django 4.1.5 on 2023-05-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_rename_timestamp_token_doble_autenticacion_admonglobal_timestamp_token_double_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysadmin',
            name='autorize_account',
            field=models.BooleanField(default=False),
        ),
    ]
