# Generated by Django 4.1.5 on 2023-06-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_admonglobal_is_authorize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='token_bot',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
