# Generated by Django 4.1.5 on 2023-06-04 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_admonglobal_timestamp_token_double_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 4, 31, 57, 73125, tzinfo=datetime.timezone.utc)),
        ),
    ]
