# Generated by Django 4.1.5 on 2023-06-05 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_admonglobal_token_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admonglobal',
            name='is_authorize',
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 16, 28, 52, 773768, tzinfo=datetime.timezone.utc)),
        ),
    ]
