# Generated by Django 3.2.18 on 2023-06-05 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_admonglobal_token_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 6, 15, 4, 606942, tzinfo=utc)),
        ),
    ]
