# Generated by Django 4.1.5 on 2023-06-05 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_remove_admonglobal_is_authorize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 17, 40, 40, 617544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='admonglobal',
            name='token_double_auth',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
