# Generated by Django 4.1.5 on 2023-06-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_admonglobal_passwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysadmin',
            old_name='password',
            new_name='passwd',
        ),
        migrations.RenameField(
            model_name='sysadmin',
            old_name='nickname',
            new_name='user_name',
        ),
    ]
