# Generated by Django 4.1.5 on 2023-06-05 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_admonglobal_timestamp_token_double_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admonglobal',
            name='timestamp_token_double_auth',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 11, 29, 405550, tzinfo=datetime.timezone.utc)),
        ),
    ]
